### ISSUE TITLE
Drupal theme dropdown not working

### ISSUE THREAD

**Issue by cluke009** [Lullabot/storybook-drupal-addon#24]
I have a similar issue to this one: https://github.com/Lullabot/storybook-drupal-addon/issues/12

It seems the only issue is with "supportedDrupalThemes" not populating the storybook dropdown though. 

The error in the dropdown is "No themes in parameters".

If I change the "drupalTheme" to be bartik for instance it will actually update storybook and pull the css and js from the correct theme. There is just no way to change the theme without editing the preview.js file.

The CL Example Components are getting loaded as expected and the correct frontend files are pulled but with the dropdown not populating its not exactly clear things are actually working.

- Drupal 9.4.7
- PHP 8.0.10
- MySQL 10.4.15-MariaDB-1:10.4.15+maria~stretch
- NPM 8.1.3
- Node v14.20.1
- Storybook 6.5.12
- @lullabot/storybook-drupal-addon 1.0.24

`main.js`

```js
module.exports = {
  "stories": [
    "../web/themes/**/*.stories.mdx",
    "../web/themes/**/*.stories.@(json|yml)",
    "../web/modules/**/*.stories.mdx",
    "../web/modules/**/*.stories.@(json|yml)",
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    '@lullabot/storybook-drupal-addon',
  ],
  "framework": "@storybook/server",
  "core": {
    "builder": "@storybook/builder-webpack5"
  },
  reactOptions: {
    fastRefresh: true,
  },
}
```

`preview.js`

```js
export const parameters = {
  server: {
    url: 'http://clserver.lndo.site',
  },
  drupalTheme: 'stark',
  supportedDrupalThemes: {
    olivero: {title: 'Olivero'},
    claro: {title: 'Claro'},
    bartik: {title: 'Bartik'},
    stark: {title: 'Stark'},
  }
};
```

**Comment by e0ipso** [comment]
This configuration looks good. I can reproduce locally.

I think there was a regression recently that broke this.
