### ISSUE TITLE
Storybook publishing

### ISSUE THREAD

**Issue by cluke009** [Lullabot/storybook-drupal-addon#26]
I am trying to deploy my Storybook build to share with coworkers. I assumed running "build-storybook" would bundle everything up nicely into static HTML that I could then deploy. That doesn't appear to be the case though as Storybook still seems to need the Drupal backend. On the CLserver module page it says not to enable it in production so I am curious what the recommended way to publish is.

![image](https://user-images.githubusercontent.com/199249/215844074-f232e6ca-a53b-4060-8d19-4a22bf4c5f23.png)

**Comment by e0ipso** [comment]
Did you follow the instructions here?

https://git.drupalcode.org/project/cl_server/-/blob/1.x/docs/storybook.md

If you did, have you checked the web console?

**Comment by cluke009** [comment]
I forgot to update the url for the new environment. Everything is working fine locally. I am also able to get things working if I enable the cl server on the production machine. I'm fine using that approach but its specifically stated that it is a security risk. Appreciatte all the great work you are doing. I'll keep plugging away at it and see if I can find a work around.

**Comment by e0ipso** [comment]
Thanks @cluke009. Let us know if you have any more updates.

**Comment by robmaurizi** [comment]
@e0ipso Why does the storybook-build output still require the Drupal backend? Shouldn't that build process take a snapshot from Drupal at the time and generate static files that can be loaded in place of the Drupal output? That seems to be the whole point of running the build script in the first place.
