### ISSUE TITLE
Error 500 on fresh install when visiting a component in Storybook

### ISSUE THREAD

**Issue by mrosati84** [Lullabot/storybook-drupal-addon#28]
Hello,
after a lot of struggle i got this thing "almost" running. Now after enabling CORS (you should mention it somewhere), i get an error 500:

```
TypeError: Drupal\cl_server\Controller\ServerEndpointController::findExtensionName(): Argument #1 ($path) must be of type string, null given, called in /opt/drupal/web/modules/contrib/cl_server/src/Controller/ServerEndpointController.php on line 121 in Drupal\cl_server\Controller\ServerEndpointController->findExtensionName() (line 182 of /opt/drupal/web/modules/contrib/cl_server/src/Controller/ServerEndpointController.php).
```

The "Use the CL Server endpoint" permission is set to anonymous user because SB runs on port 6006 and can't share the same Drupal session.

Thanks.

p.s.
please also update your doc and write some notes on what node version to use, it does not work on newer versione, i got it running only on `16.13`...

**Comment by jsantos-ut** [comment]
Same here, using node 16.13 did not fix the issue for me.

**Comment by e0ipso** [comment]
:wave: what is the version of CL Server you are running? I imagine you are running CL Components, correct?

**Comment by agarzola** [comment]
@e0ipso I’m seeing this issue with `cl_server` 1.0.0-rc5.

**Comment by rosenstrauch** [comment]
seeing this with         "drupal/cl_server": "^2.0@alpha", when trying to use it with sdc experimental too

**Comment by e0ipso** [comment]
Thanks for the reports. I see a couple different issues here. However none are related to this addon.

These issues should be moved to the correct project: https://www.drupal.org/project/cl_server. Can you please create them, so they can be resolved there?

Thanks for understanding.
