### ISSUE TITLE
Make the plugin work without a Drupal instance dependency

### ISSUE THREAD

**Issue by theodorosploumis** [Lullabot/storybook-drupal-addon#32]
It seems that this plugin needs a running Drupal instance to work. 

As far as I can understand, on [fetchStoryHtml.ts](https://github.com/Lullabot/storybook-drupal-addon/blob/main/src/fetchStoryHtml.ts) we fetch the Drupal HTML for a specific theme and render it within the Storybook iframe. Mainly to get the CSS/JS assets that come from Drupal.

I am wondering if we could **skip this process completely** and get all the theme assets on JS through a dynamic file search. It sounds difficult because we do not know which of them are actually used on every page or which modules are enabled.

This is the "final step" to make Theming independent from Drupal and become a fully theme-decoupled CMS.

**Comment by e0ipso** [comment]
I don't think we should make Drupal theming independent from Drupal. There are other projects focused on that like Emulsify, Wingsuit, etc based on Twig.js. I don't like the Twig.js approach for the reasons stated in https://www.lullabot.com/articles/component-libraries-drupal

My hot take is that I think that you need to have a Drupal local to theme for Drupal.
