### ISSUE TITLE
Does it work with single directory components? 

### ISSUE THREAD

**Issue by yustinTR** [Lullabot/storybook-drupal-addon#46]
I use the single directory components module but i cant get it to work.

this is a example of a component
![Scherm­afbeelding 2023-11-02 om 17 45 20](https://github.com/Lullabot/storybook-drupal-addon/assets/36407624/31bdb529-e1c0-45b4-95b9-78550452df94)

**Comment by e0ipso** [comment]
Yes, it works with SDC via CL Server.

**Comment by emb03** [comment]
Do we still need to install CL Server or is it included in the Storybook Drupal module de facto?
