### ISSUE TITLE
Invalid value of '@storybook/server' in the 'framework' field of Storybook config.

### ISSUE THREAD

**Issue by yustinTR** [Lullabot/storybook-drupal-addon#47]
SB_CORE-COMMON_0002 (InvalidFrameworkNameError): Invalid value of '@storybook/server' in the 'framework' field of Storybook config.

I want to run storybook version 7.5.3, but it doesnt seem to like the server as a framework.

**Comment by arnalyse** [comment]
Hey @yustinTR, please try the following: 

remove these lines:

```js
framework: '@storybook/server',
core: {
  builder: '@storybook/builder-webpack5'
},
```

and replace them with these:

```js
framework: {
  name: "@storybook/server-webpack5",
  options: {},
},
```

**Comment by e0ipso** [comment]
This was addressed in the configuration for [CL Server](https://git.drupalcode.org/project/cl_server/-/blob/2.x/docs/storybook.md?ref_type=heads).

Thanks for your contribution!
